### ISSUE TITLE
Avoid call to wp_get_object_terms()

### ISSUE THREAD

**Issue by keesiemeijer** [LezWatch/lwtv-plugin#203]
Hi,

I've noticed terms are included (and excluded) in the shortcode for similar shows. By adding `related="false"` to [the shortcode](https://github.com/LezWatch/lwtv-plugin/blob/e3c5691879631332fa707e26aa4594e7d1480e8a/cpts/shows/shows-like-this.php#L65) you can can avoid a call to `wp_get_object_terms()` made by the plugin. The results should be the same (as only terms from the taxonomies you want to query by are included)

Also, the `$terms_array` and `$tags_array` variables are never declared as an array in the [generate](https://github.com/LezWatch/lwtv-plugin/blob/e3c5691879631332fa707e26aa4594e7d1480e8a/cpts/shows/shows-like-this.php#L27) method. I think this could lead to errors or notices for posts without terms or tags.

**Comment by Ipstenu** [comment]
It's a little convoluted, but every post this is on has to have terms. If you try to save it without any, it adds one to ensure that's true. `$terms_array` will always exist and always be an array. `$tags_array` sometimes exists but with the empty() check, it seems to avoid errors.

I re-read https://keesiemeijer.wordpress.com/related-posts-by-taxonomy/#related and it looks like you cannot use exclude AND include together, so I'll toss that in! Thank you!

**Comment by keesiemeijer** [comment]
You can use include and exclude together. It used to be the case that you couldn't. The documentation for that wasn't updated correctly. I've updated it so it doesn't mention that anymore. Thanks

**Comment by Ipstenu** [comment]
What's the functional difference between saying 'related=false' and using both include and exclude?

**Comment by keesiemeijer** [comment]
The `related` attribute only has influence over the `terms` and `include_terms` attributes, not over the `exclude_terms` attribute. It's a back compatibility thing for when I originally thought only terms from the post to get related posts for should be able to be included. I've stepped away from that because you should be able to query by any term you want.

So basically there are restrictions on what terms you can use for the `terms` and `include_terms` attribute. If you set `related` to false and provide your own terms, there are none (and no extra database call is needed).

Since a few versions ago you can use `exclude_terms` and `include_terms` together, I've forgot to update the documentation.

It's all a bit convoluted and the naming a bit odd.

**Comment by keesiemeijer** [comment]
Hi,

The `terms` and `related` parameters are [deprecated in the next version](https://github.com/keesiemeijer/related-posts-by-taxonomy/blob/da1a9f65f475f9e85b22aa2376d39d9ccf9eb240/readme.txt#L150). It's all just a bit too complicated and it's not clear anymore why I added these in the first place.

`include_terms` will now accept any terms without restrictions. This is what most users expect anyway. It's a change that hopefully doesn't affect to many users negatively.

You can leave the `related="false"` in, or remove it in the next version (same results).
